---
title: "Analysis on cancer dataset"
output:
  pdf_document: default
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
#install.packages("knitr")
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#install.packages("bnlearn")
library(bnlearn)
#source("http://bioconductor.org/biocLite.R")
#biocLite("Rgraphviz")
#if (!requireNamespace("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")
#BiocManager::install()
#BiocManager::install(c("Rgraphviz"))
library(Rgraphviz)
library(ggplot2)
install.packages("pcalg")
#source("http://bioconductor.org/biocLite.R") 
#BiocManager::install(c("RBGL"))
library(RBGL)
library(pcalg)
library(ROCR)
library(PRROC)
```


```{r}
cancer <- read.csv("data/Cancer/cancer_mut.csv", header = TRUE)
cancer[]= lapply(cancer, as.factor)
INT<-sapply(1:5,function(x){which(cancer$INT==x)})

nodes<-names(cancer[1:5])
names(INT)<-nodes



start_cancer<-random.graph(nodes=nodes,method="melancon",num=100,burn.in=10^1, every=50)
netlist<-lapply(start_cancer,function(net){tabu(cancer[,1:5],score="mbde",iss=1,exp=INT,start=net,tabu=50)})
intscore_cancer<-custom.strength(netlist,nodes=nodes,cpdag=FALSE)
dag.mbde_cancer<-averaged.network(intscore_cancer)
graphviz.plot(dag.mbde_cancer)
compare((dag.cancer_groundtruth),(dag.mbde_cancer))


knowledge_scores <- intscore_cancer[,1:3]
knowledge_scores[,3]<- 0.2

knowledge_scores$strength[c(12)] <- 0.5

beta <- data.frame(from=knowledge_scores[,1], to = knowledge_scores[,2], prob=knowledge_scores[,3],stringsAsFactors = FALSE)
netlist_prior<-lapply(start_cancer,function(net){tabu(cancer[,1:5],score="mbde", prior = "cs",beta=beta,iss=1,exp=INT,start=net,tabu=50)})

netlist_prior_marginal<-lapply(start_cancer,function(net){tabu(cancer[,1:5],score="mbde", prior = "marginal",iss=1,exp=INT,start=net,tabu=50)})

netlist_prior_vsp<-lapply(start_cancer,function(net){tabu(cancer[,1:5],score="mbde", prior = "vsp",iss=1,exp=INT,start=net,tabu=50)})



intscore_cancer_prior<-custom.strength(netlist_prior,nodes=nodes,cpdag=FALSE)

intscore_cancer_prior_marginal<-custom.strength(netlist_prior_marginal,nodes=nodes,cpdag=FALSE)

intscore_cancer_prior_vsp<-custom.strength(netlist_prior_vsp,nodes=nodes,cpdag=FALSE)
```

```{r}
#..............finding the labels from the groundtruth networks...............
cancer_groundtruth <- read.csv("data/Cancer/refNetwork.csv", header = TRUE)
labels_cancer <- intscore_cancer[,1:3]
labels_cancer[,3] <- 0
merge_cancer <- merge(intscore_cancer,cancer_groundtruth,by.x=c('from','to'),by.y=c('from','to'),all.x=TRUE)


for (i in 1:nrow(merge_cancer)){
  if (!is.na(merge_cancer[i,5])){
    from = merge_cancer[i,1]
    to = merge_cancer[i,2]
  }
  labels_cancer[which((labels_cancer$from %in% from) & (labels_cancer$to %in% to)),3] <- 1
}

for (i in 1:nrow(labels_cancer)){
  if (labels_cancer[i,3]==1){
    from = labels_cancer[i,1]
    to = labels_cancer[i,2]
    labels_cancer[which((labels_cancer$from %in% to) & (labels_cancer$to %in% from)),][3] <- 1
  }
}
```
```{r}
#.................ROC curve analysis for cancer Data...........................
PRROC_obj1 <- roc.curve(scores.class0 = intscore_cancer[,3], weights.class0=labels_cancer[,3],curve=TRUE)
PRROC_obj2 <- roc.curve(scores.class0 = intscore_cancer_prior[,3], weights.class0=labels_cancer[,3],curve=TRUE)
PRROC_obj3 <- roc.curve(scores.class0 = intscore_cancer_prior_marginal[,3], weights.class0=labels_cancer[,3],curve=TRUE)
PRROC_obj4 <- roc.curve(scores.class0 = intscore_cancer_prior_vsp[,3], weights.class0=labels_cancer[,3],curve=TRUE)
```
```{r}
#.................ROC curve plot for cancer Data...........................
tiff("/Users/megha/Documents/Kg2Causal/Plots/cancerROC.tiff", units="in", width=5, height=5, res=600)
p = ggplot() +     geom_line(data = data.frame(PRROC_obj1$curve), aes(x=X1,y=X2,color="red")) + geom_line(data = data.frame(PRROC_obj2$curve), aes(x=X1,y=X2,color = "blue")) + 
  geom_line(data = data.frame(PRROC_obj3$curve), aes(x=X1,y=X2,color="green"))+
  geom_line(data = data.frame(PRROC_obj4$curve), aes(x=X1,y=X2,color="brown"))+ xlab('FP rate') + ylab('TP rate') + geom_smooth(span = 0.5) +scale_color_identity(name = "Method",breaks = c("blue","red","green","brown"))+theme(text = element_text(size=30),
        axis.text.x = element_text(hjust=1)) 
plot(p)
dev.off()
       
```
```{r}
#.................PR curve analysis for cancer Data...........................
PRROC_obj1 <- pr.curve(scores.class0 = intscore_cancer[,3], weights.class0=labels_cancer[,3],curve=TRUE)
PRROC_obj2 <- pr.curve(scores.class0 = intscore_cancer_prior[,3], weights.class0=labels_cancer[,3],curve=TRUE)
PRROC_obj3 <- pr.curve(scores.class0 = intscore_cancer_prior_marginal[,3], weights.class0=labels_cancer[,3],curve=TRUE)
PRROC_obj4 <- pr.curve(scores.class0 = intscore_cancer_prior_vsp[,3], weights.class0=labels_cancer[,3],curve=TRUE)
```
```{r}
#.................PR curve plot for cancer Data...........................
tiff("/Users/megha/Documents/Kg2Causal/cancerPR.tiff", units="in", width=5, height=5, res=600)
p = ggplot() +     geom_line(data = data.frame(PRROC_obj1$curve), aes(x=X1,y=X2,color="red")) + geom_line(data = data.frame(PRROC_obj2$curve), aes(x=X1,y=X2,color = "blue")) + 
  geom_line(data = data.frame(PRROC_obj3$curve), aes(x=X1,y=X2,color="green"))+
  geom_line(data = data.frame(PRROC_obj4$curve), aes(x=X1,y=X2,color="brown"))+ xlab('Recall') + ylab('Precision') + geom_smooth(span = 0.5) +scale_color_identity(name = "Method",breaks = c("blue","red","green","brown"))+theme(text = element_text(size=30),
        axis.text.x = element_text(hjust=1)) 
plot(p)
dev.off()
       
```

```{r}
#.................F1 score vs cutoff analysis for cancer Data...........................
pred <- prediction(intscore_cancer[,3], labels_cancer[,3])
f_cancer <- performance(pred,"f")
fscore_cancer = data.frame("Cutoff"=f_cancer@x.values[[1]],"Precision-Recall F measure"=f_cancer@y.values[[1]])

pred <- prediction(intscore_cancer_prior[,3], labels_cancer[,3])
f_cancer <- performance(pred,"f")
fscore_cancer_prior = data.frame("Cutoff"=f_cancer@x.values[[1]],"Precision-Recall F measure"=f_cancer@y.values[[1]])

pred <- prediction(intscore_cancer_prior_marginal[,3], labels_cancer[,3])
f_cancer <- performance(pred,"f")
fscore_cancer_marginal = data.frame("Cutoff"=f_cancer@x.values[[1]],"Precision-Recall F measure"=f_cancer@y.values[[1]])

pred <- prediction(intscore_cancer_prior_vsp[,3], labels_cancer[,3])
f_cancer <- performance(pred,"f")
fscore_cancer_vsp = data.frame("Cutoff"=f_cancer@x.values[[1]],"Precision-Recall F measure"=f_cancer@y.values[[1]])
```

```{r}
#.................F1 score vs cutoff plotting for cancer Data...........................
tiff("/Users/megha/Documents/Kg2Causal/cancerF1.tiff", units="in", width=5, height=5, res=600)
p = ggplot() +     geom_line(data = fscore_cancer, aes(x=Cutoff,y=Precision.Recall.F.measure,color="red")) + geom_line(data = fscore_cancer_prior, aes(x=Cutoff,y=Precision.Recall.F.measure,color = "blue")) + 
  geom_line(data = data.frame(fscore_cancer_marginal), aes(x=Cutoff,y=Precision.Recall.F.measure,color="green"))+
  geom_line(data = data.frame(fscore_cancer_vsp), aes(x=Cutoff,y=Precision.Recall.F.measure,color="brown"))+ xlab('Cutoff') + ylab('F1 measure') + geom_smooth(span = 0.5) +scale_color_identity(name = "Method",breaks = c("blue","red","green","brown"))+theme(text = element_text(size=30),
        axis.text.x = element_text(hjust=1)) 
plot(p)
dev.off()
```


```{r}
#.................accuracy vs cutoff analysis for cancer Data.....................
pred <- prediction(intscore_cancer[,3], labels_cancer[,3])
f_cancer <- performance(pred,"acc")
fscore_cancer = data.frame("Cutoff"=f_cancer@x.values[[1]],"Accuracy"=f_cancer@y.values[[1]])


pred <- prediction(intscore_cancer_prior[,3], labels_cancer[,3])
f_cancer <- performance(pred,"acc")
fscore_cancer_prior = data.frame("Cutoff"=f_cancer@x.values[[1]],"Accuracy"=f_cancer@y.values[[1]])

pred <- prediction(intscore_cancer_prior_marginal[,3], labels_cancer[,3])
f_cancer <- performance(pred,"acc")
fscore_cancer_marginal = data.frame("Cutoff"=f_cancer@x.values[[1]],"Accuracy"=f_cancer@y.values[[1]])


pred <- prediction(intscore_cancer_prior_vsp[,3], labels_cancer[,3])
f_cancer <- performance(pred,"acc")
fscore_cancer_vsp = data.frame("Cutoff"=f_cancer@x.values[[1]],"Accuracy"=f_cancer@y.values[[1]])
```

```{r}
#.................accuracy vs cutoff plotting for cancer Data...........................
tiff("/Users/megha/Documents/Kg2Causal/cancerAcc.tiff", units="in", width=5, height=5, res=600)
p = ggplot() +     geom_line(data = fscore_cancer, aes(x=Cutoff,y=Precision.Recall.F.measure,color="red")) + geom_line(data = fscore_cancer_prior, aes(x=Cutoff,y=Precision.Recall.F.measure,color = "blue")) + 
  geom_line(data = data.frame(fscore_cancer_marginal), aes(x=Cutoff,y=Precision.Recall.F.measure,color="green"))+
  geom_line(data = data.frame(fscore_cancer_vsp), aes(x=Cutoff,y=Precision.Recall.F.measure,color="brown"))+ xlab('Cutoff') + ylab('Accuracy') + geom_smooth(span = 0.5) +scale_color_identity(name = "Method",breaks = c("blue","red","green","brown"))+theme(text = element_text(size=30),
        axis.text.x = element_text(hjust=1)) 
plot(p)
dev.off()       
```



Using Learn and Vote

```{r}
obs=cancer_mut[1:500,]
exp1=cancer_mut[501:1000,]
```
Using Uniform prior

```{r}
#obs
INT<-sapply(1:5,function(x){which(obs$INT==x)})
nodes<-names(obs[1:5])
names(INT)<-nodes
start<-random.graph(nodes=nodes,method="melancon",num=500,burn.in=10^5, every=50)
netlist = lapply(start, function(net) {tabu(obs[,1:5], score = "mbde", exp=INT, iss = 1, start = net, tabu=50) })
arcs_obs = custom.strength(netlist, nodes = nodes, cpdag = FALSE)
#-----------------------------------------------------------------------------------------------------------------

#exp1
INT<-sapply(1:5,function(x){which(exp1$INT==x)})
nodes<-names(exp1[1:5])
names(INT)<-nodes
#start<-random.graph(nodes=nodes,method="melancon",num=500,burn.in=10^5, every=50)
netlist<-lapply(start,function(net){tabu(exp1[,1:5],score="mbde",exp=INT,iss=1,start=net,tabu=50)})
arcs_mut1 = custom.strength(netlist, nodes = nodes, cpdag = FALSE)
```


```{r}
#average
intscore_pooled=arcs_obs
intscore_pooled[,3]=intscore_pooled[,3]  + arcs_mut1[,3]
intscore_pooled[,4]=intscore_pooled[,4] + arcs_mut1[,4]
intscore_pooled[,3]=intscore_pooled[,3]/2
intscore_pooled[,4]=intscore_pooled[,4]/2
```

Using KG as prior

```{r}
#obs
INT<-sapply(1:5,function(x){which(obs$INT==x)})
nodes<-names(obs[1:5])
names(INT)<-nodes
start<-random.graph(nodes=nodes,method="melancon",num=500,burn.in=10^5, every=50)
netlist = lapply(start, function(net) {tabu(obs[,1:5], score="mbde", prior = "cs",beta=beta,iss=1,exp=INT,start=net,tabu=50) })
arcs_obs = custom.strength(netlist, nodes = nodes, cpdag = FALSE)
#-----------------------------------------------------------------------------------------------------------------

#exp1
INT<-sapply(1:5,function(x){which(exp1$INT==x)})
nodes<-names(exp1[1:5])
names(INT)<-nodes
#start<-random.graph(nodes=nodes,method="melancon",num=500,burn.in=10^5, every=50)
netlist<-lapply(start,function(net){tabu(exp1[,1:5],score="mbde", prior = "cs",beta=beta,iss=1,exp=INT,start=net,tabu=50)})
arcs_mut1 = custom.strength(netlist, nodes = nodes, cpdag = FALSE)
```


```{r}
#average
intscore_pooled_kg=arcs_obs
intscore_pooled_kg[,3]=intscore_pooled_kg[,3]  + arcs_mut1[,3]
intscore_pooled_kg[,4]=intscore_pooled_kg[,4] + arcs_mut1[,4]
intscore_pooled_kg[,3]=intscore_pooled_kg[,3]/2
intscore_pooled_kg[,4]=intscore_pooled_kg[,4]/2
```

Using Marginal prior

```{r}
#obs
INT<-sapply(1:5,function(x){which(obs$INT==x)})
nodes<-names(obs[1:5])
names(INT)<-nodes
start<-random.graph(nodes=nodes,method="melancon",num=500,burn.in=10^5, every=50)
netlist = lapply(start, function(net) {tabu(obs[,1:5], score = "mbde", exp=INT, prior = "marginal", iss = 1, start = net, tabu=50) })
arcs_obs = custom.strength(netlist, nodes = nodes, cpdag = FALSE)
#-----------------------------------------------------------------------------------------------------------------

#exp1
INT<-sapply(1:5,function(x){which(exp1$INT==x)})
nodes<-names(exp1[1:5])
names(INT)<-nodes
#start<-random.graph(nodes=nodes,method="melancon",num=500,burn.in=10^5, every=50)
netlist<-lapply(start,function(net){tabu(exp1[,1:5],score="mbde",exp=INT, prior = "marginal",iss=1,start=net,tabu=50)})
arcs_mut1 = custom.strength(netlist, nodes = nodes, cpdag = FALSE)
```


```{r}
#average
intscore_pooled_marginal=arcs_obs
intscore_pooled_marginal[,3]=intscore_pooled_marginal[,3]  + arcs_mut1[,3]
intscore_pooled_marginal[,4]=intscore_pooled_marginal[,4] + arcs_mut1[,4]
intscore_pooled_marginal[,3]=intscore_pooled_marginal[,3]/2
intscore_pooled_marginal[,4]=intscore_pooled_marginal[,4]/2
```


Using vsp prior

```{r}
#obs
INT<-sapply(1:5,function(x){which(obs$INT==x)})
nodes<-names(obs[1:5])
names(INT)<-nodes
start<-random.graph(nodes=nodes,method="melancon",num=500,burn.in=10^5, every=50)
netlist = lapply(start, function(net) {tabu(obs[,1:5], score = "mbde", exp=INT, prior = "vsp", iss = 1, start = net, tabu=50) })
arcs_obs = custom.strength(netlist, nodes = nodes, cpdag = FALSE)
#-----------------------------------------------------------------------------------------------------------------

#exp1
INT<-sapply(1:5,function(x){which(exp1$INT==x)})
nodes<-names(exp1[1:5])
names(INT)<-nodes
#start<-random.graph(nodes=nodes,method="melancon",num=500,burn.in=10^5, every=50)
netlist<-lapply(start,function(net){tabu(exp1[,1:5],score="mbde",exp=INT, prior = "vsp",iss=1,start=net,tabu=50)})
arcs_mut1 = custom.strength(netlist, nodes = nodes, cpdag = FALSE)
```


```{r}
#average
intscore_pooled_vsp=arcs_obs
intscore_pooled_vsp[,3]=intscore_pooled_vsp[,3]  + arcs_mut1[,3]
intscore_pooled_vsp[,4]=intscore_pooled_vsp[,4] + arcs_mut1[,4]
intscore_pooled_vsp[,3]=intscore_pooled_vsp[,3]/2
intscore_pooled_vsp[,4]=intscore_pooled_vsp[,4]/2
```


```{r}
#.................ROC curve analysis for asia Data...........................
PRROC_obj1 <- roc.curve(scores.class0 = intscore_pooled[,3], weights.class0=labels_asia[,3],curve=TRUE)
PRROC_obj2 <- roc.curve(scores.class0 = intscore_pooled_kg[,3], weights.class0=labels_asia[,3],curve=TRUE)
PRROC_obj3 <- roc.curve(scores.class0 = intscore_pooled_marginal[,3], weights.class0=labels_asia[,3],curve=TRUE)
PRROC_obj4 <- roc.curve(scores.class0 = intscore_pooled_vsp[,3], weights.class0=labels_asia[,3],curve=TRUE)
```

```{r}
#.................ROC curve analysis for asia Data...........................
PRROC_obj1 <- pr.curve(scores.class0 = intscore_pooled[,3], weights.class0=labels_asia[,3],curve=TRUE)
PRROC_obj2 <- pr.curve(scores.class0 = intscore_pooled_kg[,3], weights.class0=labels_asia[,3],curve=TRUE)
PRROC_obj3 <- pr.curve(scores.class0 = intscore_pooled_marginal[,3], weights.class0=labels_asia[,3],curve=TRUE)
PRROC_obj4 <- pr.curve(scores.class0 = intscore_pooled_vsp[,3], weights.class0=labels_asia[,3],curve=TRUE)
```


