---
title: "Analysis on Asia dataset"
output:
  pdf_document: default
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
#install.packages("knitr")
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#install.packages("bnlearn")
library(bnlearn)
#source("http://bioconductor.org/biocLite.R")
#biocLite("Rgraphviz")
#if (!requireNamespace("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")
#BiocManager::install()
#BiocManager::install(c("Rgraphviz"))
library(Rgraphviz)
library(ggplot2)
#install.packages("pcalg")
#source("http://bioconductor.org/biocLite.R") 
#BiocManager::install(c("RBGL"))
library(RBGL)
library(pcalg)
library(ROCR)
library(PRROC)
```


```{r}
asia <- read.csv("data/Asia/asia_mut.csv", header = TRUE)
asia[]= lapply(asia, as.factor)
INT<-sapply(1:8,function(x){which(asia$INT==x)})

nodes<-names(asia[1:8])
names(INT)<-nodes
dag.asia_groundtruth = model2network("[A][S][T|A][L|S][B|S][D|B:E][E|T:L][X|E]")

start_asia<-random.graph(nodes=nodes,method="melancon",num=100,burn.in=10^1, every=50)
netlist<-lapply(start_asia,function(net){tabu(asia[,1:8],score="mbde",iss=1,exp=INT,start=net,tabu=50)})
intscore_asia<-custom.strength(netlist,nodes=nodes,cpdag=FALSE)
dag.mbde_asia<-averaged.network(intscore_asia)
graphviz.plot(dag.mbde_asia)
compare((dag.asia_groundtruth),(dag.mbde_asia))


knowledge_scores <- intscore_asia[,1:3]
knowledge_scores[,3]<- 0.2

knowledge_scores$strength[c(35,26,42,11,19,42)] <- 0.5

beta <- data.frame(from=knowledge_scores[,1], to = knowledge_scores[,2], prob=knowledge_scores[,3],stringsAsFactors = FALSE)

netlist_prior<-lapply(start_asia,function(net){tabu(asia[,1:8],score="mbde", prior = "cs",beta=beta,iss=1,exp=INT,start=net,tabu=50)})

netlist_prior_marginal<-lapply(start_asia,function(net){tabu(asia[,1:8],score="mbde", prior = "marginal",exp=INT,iss=1,start=net,tabu=50)})

netlist_prior_vsp<-lapply(start_asia,function(net){tabu(asia[,1:8],score="mbde", prior = "vsp",exp=INT,iss=1,start=net,tabu=50)})



intscore_asia_prior<-custom.strength(netlist_prior,nodes=nodes,cpdag=FALSE)

intscore_asia_prior_marginal<-custom.strength(netlist_prior_marginal,nodes=nodes,cpdag=FALSE)

intscore_asia_prior_vsp<-custom.strength(netlist_prior_vsp,nodes=nodes,cpdag=FALSE)
```

```{r}
#..............finding the labels from the groundtruth networks...............
asia_groundtruth <- read.csv("data/Asia/refNetwork.csv", header = TRUE)
labels_asia <- intscore_asia[,1:3]
labels_asia[,3] <- 0
merge_asia <- merge(intscore_asia,asia_groundtruth,by.x=c('from','to'),by.y=c('from','to'),all.x=TRUE)


for (i in 1:nrow(merge_asia)){
  if (!is.na(merge_asia[i,5])){
    from = merge_asia[i,1]
    to = merge_asia[i,2]
  }
  labels_asia[which((labels_asia$from %in% from) & (labels_asia$to %in% to)),3] <- 1
}

for (i in 1:nrow(labels_asia)){
  if (labels_asia[i,3]==1){
    from = labels_asia[i,1]
    to = labels_asia[i,2]
    labels_asia[which((labels_asia$from %in% to) & (labels_asia$to %in% from)),][3] <- 1
  }
}
```


```{r}
#.................ROC curve analysis for asia Data...........................
PRROC_obj1 <- roc.curve(scores.class0 = intscore_asia[,3], weights.class0=labels_asia[,3],curve=TRUE)
PRROC_obj2 <- roc.curve(scores.class0 = intscore_asia_prior[,3], weights.class0=labels_asia[,3],curve=TRUE)
PRROC_obj3 <- roc.curve(scores.class0 = intscore_asia_prior_marginal[,3], weights.class0=labels_asia[,3],curve=TRUE)
PRROC_obj4 <- roc.curve(scores.class0 = intscore_asia_prior_vsp[,3], weights.class0=labels_asia[,3],curve=TRUE)
```

```{r}
#.................ROC Plot for asia Data...........................
tiff("/Users/megha/Work_Space/CausalAnalysis_with_KGprior/Plots/asiaROC.tiff", units="in", width=5, height=5, res=600)

p = ggplot() +     geom_line(data = data.frame(PRROC_obj1$curve), aes(x=X1,y=X2,color="red")) + geom_line(data = data.frame(PRROC_obj2$curve), aes(x=X1,y=X2,color = "blue")) + 
  geom_line(data = data.frame(PRROC_obj3$curve), aes(x=X1,y=X2,color="green"))+
  geom_line(data = data.frame(PRROC_obj4$curve), aes(x=X1,y=X2,color="brown"))+ xlab('FP rate') + ylab('TP rate') + geom_smooth(span = 0.5) +scale_color_identity(name = "Method",breaks = c("blue","red","green","brown")) +
    theme(text = element_text(size=30),
        axis.text.x = element_text(hjust=1)) 
plot(p)
dev.off() 
```  

```{r}
#.................PR curve analysis for asia Data...........................
PRROC_obj1 <- pr.curve(scores.class0 = intscore_asia[,3], weights.class0=labels_asia[,3],curve=TRUE)
PRROC_obj2 <- pr.curve(scores.class0 = intscore_asia_prior[,3], weights.class0=labels_asia[,3],curve=TRUE)
PRROC_obj3 <- pr.curve(scores.class0 = intscore_asia_prior_marginal[,3], weights.class0=labels_asia[,3],curve=TRUE)
PRROC_obj4 <- pr.curve(scores.class0 = intscore_asia_prior_vsp[,3], weights.class0=labels_asia[,3],curve=TRUE)
```

```{r}
#.................PR Plot for asia Data...........................
tiff("/Users/megha/Work_Space/CausalAnalysis_with_KGprior/Plots/asiaPR.tiff", units="in", width=5, height=5, res=600)

p = ggplot() +     geom_line(data = data.frame(PRROC_obj1$curve), aes(x=X1,y=X2,color="red")) + geom_line(data = data.frame(PRROC_obj2$curve), aes(x=X1,y=X2,color = "blue")) + 
  geom_line(data = data.frame(PRROC_obj3$curve), aes(x=X1,y=X2,color="green"))+
  geom_line(data = data.frame(PRROC_obj4$curve), aes(x=X1,y=X2,color="brown"))+ xlab('Recall') + ylab('Precision') + geom_smooth(span = 0.5) +scale_color_identity(name = "Method",breaks = c("blue","red","green","brown")) +
    theme(text = element_text(size=30),
        axis.text.x = element_text(hjust=1)) 
plot(p)
dev.off() 
```

```{r}
#.................F1 score vs cutoff analysis for asia Data...........................
pred <- prediction(intscore_asia[,3], labels_asia[,3])
f_asia <- performance(pred,"f")
fscore_asia = data.frame("Cutoff"=f_asia@x.values[[1]],"Precision-Recall F measure"=f_asia@y.values[[1]])


pred <- prediction(intscore_asia_prior[,3], labels_asia[,3])
f_asia <- performance(pred,"f")
fscore_asia_prior = data.frame("Cutoff"=f_asia@x.values[[1]],"Precision-Recall F measure"=f_asia@y.values[[1]])

pred <- prediction(intscore_asia_prior_marginal[,3], labels_asia[,3])
f_asia <- performance(pred,"f")
fscore_asia_marginal = data.frame("Cutoff"=f_asia@x.values[[1]],"Precision-Recall F measure"=f_asia@y.values[[1]])


pred <- prediction(intscore_asia_prior_vsp[,3], labels_asia[,3])
f_asia <- performance(pred,"f")
fscore_asia_vsp = data.frame("Cutoff"=f_asia@x.values[[1]],"Precision-Recall F measure"=f_asia@y.values[[1]])
```

```{r}
#.................F1 score vs cutoff plot for asia Data...........................
tiff("/Users/megha/Work_Space/CausalAnalysis_with_KGprior/Plots/asiaF1.tiff", units="in", width=5, height=5, res=600)
p = ggplot() +     geom_line(data = fscore_asia, aes(x=Cutoff,y=Precision.Recall.F.measure,color="red")) + geom_line(data = fscore_asia_prior, aes(x=Cutoff,y=Precision.Recall.F.measure,color = "blue")) + 
  geom_line(data = data.frame(fscore_asia_marginal), aes(x=Cutoff,y=Precision.Recall.F.measure,color="green"))+
  geom_line(data = data.frame(fscore_asia_vsp), aes(x=Cutoff,y=Precision.Recall.F.measure,color="brown"))+ xlab('Cutoff') + ylab('F1 measure') + geom_smooth(span = 0.5) +scale_color_identity(name = "Method",breaks = c("blue","red","green","brown")) +
    theme(text = element_text(size=30),
        axis.text.x = element_text(hjust=1)) 
plot(p)
dev.off()  
```

```{r}
#.................accuracy vs cutoff analysis for asia Data...........................
pred <- prediction(intscore_asia[,3], labels_asia[,3])
f_asia <- performance(pred,"acc")
fscore_asia = data.frame("Cutoff"=f_asia@x.values[[1]],"Precision-Recall F measure"=f_asia@y.values[[1]])


pred <- prediction(intscore_asia_prior[,3], labels_asia[,3])
f_asia <- performance(pred,"acc")
fscore_asia_prior = data.frame("Cutoff"=f_asia@x.values[[1]],"Precision-Recall F measure"=f_asia@y.values[[1]])

pred <- prediction(intscore_asia_prior_marginal[,3], labels_asia[,3])
f_asia <- performance(pred,"acc")
fscore_asia_marginal = data.frame("Cutoff"=f_asia@x.values[[1]],"Precision-Recall F measure"=f_asia@y.values[[1]])


pred <- prediction(intscore_asia_prior_vsp[,3], labels_asia[,3])
f_asia <- performance(pred,"acc")
fscore_asia_vsp = data.frame("Cutoff"=f_asia@x.values[[1]],"Precision-Recall F measure"=f_asia@y.values[[1]])

```

```{r}
#.................accuracy score vs cutoff plot for asia Data...........................
tiff("/Users/megha/Work_Space/CausalAnalysis_with_KGprior/Plots/asiaAcc.tiff", units="in", width=5, height=5, res=600)
p = ggplot() +     geom_line(data = fscore_asia, aes(x=Cutoff,y=Precision.Recall.F.measure,color="red")) + geom_line(data = fscore_asia_prior, aes(x=Cutoff,y=Precision.Recall.F.measure,color = "blue")) + 
  geom_line(data = data.frame(fscore_asia_marginal), aes(x=Cutoff,y=Precision.Recall.F.measure,color="green"))+
  geom_line(data = data.frame(fscore_asia_vsp), aes(x=Cutoff,y=Precision.Recall.F.measure,color="brown"))+ xlab('Cutoff') + ylab('Accuracy') + geom_smooth(span = 0.5) +scale_color_identity(name = "Method",breaks = c("blue","red","green","brown"))+
    theme(text = element_text(size=30),
        axis.text.x = element_text(hjust=1),legend.position="bottom") 
plot(p)
dev.off() 
```


Using Learn and Vote

```{r}
obs=asia_mut[1:500,]
exp1=asia_mut[501:1000,]
exp2=asia_mut[1001:1500,]
```

Using Uniform prior

```{r}
#obs
INT<-sapply(1:8,function(x){which(obs$INT==x)})
nodes<-names(obs[1:8])
names(INT)<-nodes
start<-random.graph(nodes=nodes,method="melancon",num=500,burn.in=10^5, every=50)
netlist = lapply(start, function(net) {tabu(obs[,1:8], score = "mbde", exp=INT, iss = 1, start = net, tabu=50) })
arcs_obs = custom.strength(netlist, nodes = nodes, cpdag = FALSE)
#-----------------------------------------------------------------------------------------------------------------

#exp1
INT<-sapply(1:8,function(x){which(exp1$INT==x)})
nodes<-names(exp1[1:8])
names(INT)<-nodes
#start<-random.graph(nodes=nodes,method="melancon",num=500,burn.in=10^5, every=50)
netlist<-lapply(start,function(net){tabu(exp1[,1:8],score="mbde",exp=INT,iss=1,start=net,tabu=50)})
arcs_mut1 = custom.strength(netlist, nodes = nodes, cpdag = FALSE)
#-----------------------------------------------------------------------------------------------------------------

#exp2
INT<-sapply(1:8,function(x){which(exp2$INT==x)})
nodes<-names(exp2[1:8])
names(INT)<-nodes
#start<-random.graph(nodes=nodes,method="melancon",num=500,burn.in=10^5, every=50)
netlist<-lapply(start,function(net){tabu(exp2[,1:8],score="mbde",exp=INT,iss=1,start=net,tabu=50)})
arcs_mut2 = custom.strength(netlist, nodes = nodes, cpdag = FALSE)
```


```{r}
#average
intscore_pooled=arcs_obs
intscore_pooled[,3]=intscore_pooled[,3]  + arcs_mut1[,3]+ arcs_mut2[,3]
intscore_pooled[,4]=intscore_pooled[,4] + arcs_mut1[,4]+ arcs_mut2[,4]
intscore_pooled[,3]=intscore_pooled[,3]/3
intscore_pooled[,4]=intscore_pooled[,4]/3
```

Using KG as prior

```{r}
#obs
INT<-sapply(1:8,function(x){which(obs$INT==x)})
nodes<-names(obs[1:8])
names(INT)<-nodes
start<-random.graph(nodes=nodes,method="melancon",num=500,burn.in=10^5, every=50)
netlist = lapply(start, function(net) {tabu(obs[,1:8], score="mbde", prior = "cs",beta=beta,iss=1,exp=INT,start=net,tabu=50) })
arcs_obs = custom.strength(netlist, nodes = nodes, cpdag = FALSE)
#-----------------------------------------------------------------------------------------------------------------

#exp1
INT<-sapply(1:8,function(x){which(exp1$INT==x)})
nodes<-names(exp1[1:8])
names(INT)<-nodes
#start<-random.graph(nodes=nodes,method="melancon",num=500,burn.in=10^5, every=50)
netlist<-lapply(start,function(net){tabu(exp1[,1:8],score="mbde", prior = "cs",beta=beta,iss=1,exp=INT,start=net,tabu=50)})
arcs_mut1 = custom.strength(netlist, nodes = nodes, cpdag = FALSE)
#-----------------------------------------------------------------------------------------------------------------

#exp2
INT<-sapply(1:8,function(x){which(exp2$INT==x)})
nodes<-names(exp2[1:8])
names(INT)<-nodes
#start<-random.graph(nodes=nodes,method="melancon",num=500,burn.in=10^5, every=50)
netlist<-lapply(start,function(net){tabu(exp2[,1:8],score="mbde", prior = "cs",beta=beta,iss=1,exp=INT,start=net,tabu=50)})
arcs_mut2 = custom.strength(netlist, nodes = nodes, cpdag = FALSE)
```


```{r}
#average
intscore_pooled_kg=arcs_obs
intscore_pooled_kg[,3]=intscore_pooled_kg[,3]  + arcs_mut1[,3]+ arcs_mut2[,3]
intscore_pooled_kg[,4]=intscore_pooled_kg[,4] + arcs_mut1[,4]+ arcs_mut2[,4]
intscore_pooled_kg[,3]=intscore_pooled_kg[,3]/3
intscore_pooled_kg[,4]=intscore_pooled_kg[,4]/3
```

Using Marginal prior

```{r}
#obs
INT<-sapply(1:8,function(x){which(obs$INT==x)})
nodes<-names(obs[1:8])
names(INT)<-nodes
start<-random.graph(nodes=nodes,method="melancon",num=500,burn.in=10^5, every=50)
netlist = lapply(start, function(net) {tabu(obs[,1:8], score = "mbde", exp=INT, prior = "marginal", iss = 1, start = net, tabu=50) })
arcs_obs = custom.strength(netlist, nodes = nodes, cpdag = FALSE)
#-----------------------------------------------------------------------------------------------------------------

#exp1
INT<-sapply(1:8,function(x){which(exp1$INT==x)})
nodes<-names(exp1[1:8])
names(INT)<-nodes
#start<-random.graph(nodes=nodes,method="melancon",num=500,burn.in=10^5, every=50)
netlist<-lapply(start,function(net){tabu(exp1[,1:8],score="mbde",exp=INT, prior = "marginal",iss=1,start=net,tabu=50)})
arcs_mut1 = custom.strength(netlist, nodes = nodes, cpdag = FALSE)
#-----------------------------------------------------------------------------------------------------------------

#exp2
INT<-sapply(1:8,function(x){which(exp2$INT==x)})
nodes<-names(exp2[1:8])
names(INT)<-nodes
#start<-random.graph(nodes=nodes,method="melancon",num=500,burn.in=10^5, every=50)
netlist<-lapply(start,function(net){tabu(exp2[,1:8],score="mbde",exp=INT, prior = "marginal",iss=1,start=net,tabu=50)})
arcs_mut2 = custom.strength(netlist, nodes = nodes, cpdag = FALSE)
```


```{r}
#average
intscore_pooled_marginal=arcs_obs
intscore_pooled_marginal[,3]=intscore_pooled_marginal[,3]  + arcs_mut1[,3]+ arcs_mut2[,3]
intscore_pooled_marginal[,4]=intscore_pooled_marginal[,4] + arcs_mut1[,4]+ arcs_mut2[,4]
intscore_pooled_marginal[,3]=intscore_pooled_marginal[,3]/3
intscore_pooled_marginal[,4]=intscore_pooled_marginal[,4]/3
```


Using vsp prior

```{r}
#obs
INT<-sapply(1:8,function(x){which(obs$INT==x)})
nodes<-names(obs[1:8])
names(INT)<-nodes
start<-random.graph(nodes=nodes,method="melancon",num=500,burn.in=10^5, every=50)
netlist = lapply(start, function(net) {tabu(obs[,1:8], score = "mbde", exp=INT, prior = "vsp", iss = 1, start = net, tabu=50) })
arcs_obs = custom.strength(netlist, nodes = nodes, cpdag = FALSE)
#-----------------------------------------------------------------------------------------------------------------

#exp1
INT<-sapply(1:8,function(x){which(exp1$INT==x)})
nodes<-names(exp1[1:8])
names(INT)<-nodes
#start<-random.graph(nodes=nodes,method="melancon",num=500,burn.in=10^5, every=50)
netlist<-lapply(start,function(net){tabu(exp1[,1:8],score="mbde",exp=INT, prior = "vsp",iss=1,start=net,tabu=50)})
arcs_mut1 = custom.strength(netlist, nodes = nodes, cpdag = FALSE)
#-----------------------------------------------------------------------------------------------------------------

#exp2
INT<-sapply(1:8,function(x){which(exp2$INT==x)})
nodes<-names(exp2[1:8])
names(INT)<-nodes
#start<-random.graph(nodes=nodes,method="melancon",num=500,burn.in=10^5, every=50)
netlist<-lapply(start,function(net){tabu(exp2[,1:8],score="mbde",exp=INT, prior = "vsp",iss=1,start=net,tabu=50)})
arcs_mut2 = custom.strength(netlist, nodes = nodes, cpdag = FALSE)
```


```{r}
#average
intscore_pooled_vsp=arcs_obs
intscore_pooled_vsp[,3]=intscore_pooled_vsp[,3]  + arcs_mut1[,3]+ arcs_mut2[,3]
intscore_pooled_vsp[,4]=intscore_pooled_vsp[,4] + arcs_mut1[,4]+ arcs_mut2[,4]
intscore_pooled_vsp[,3]=intscore_pooled_vsp[,3]/3
intscore_pooled_vsp[,4]=intscore_pooled_vsp[,4]/3
```


```{r}
#.................ROC curve analysis for asia Data...........................
PRROC_obj1 <- roc.curve(scores.class0 = intscore_pooled[,3], weights.class0=labels_asia[,3],curve=TRUE)
PRROC_obj2 <- roc.curve(scores.class0 = intscore_pooled_kg[,3], weights.class0=labels_asia[,3],curve=TRUE)
PRROC_obj3 <- roc.curve(scores.class0 = intscore_pooled_marginal[,3], weights.class0=labels_asia[,3],curve=TRUE)
PRROC_obj4 <- roc.curve(scores.class0 = intscore_pooled_vsp[,3], weights.class0=labels_asia[,3],curve=TRUE)
```

```{r}
#.................ROC curve analysis for asia Data...........................
PRROC_obj1 <- pr.curve(scores.class0 = intscore_pooled[,3], weights.class0=labels_asia[,3],curve=TRUE)
PRROC_obj2 <- pr.curve(scores.class0 = intscore_pooled_kg[,3], weights.class0=labels_asia[,3],curve=TRUE)
PRROC_obj3 <- pr.curve(scores.class0 = intscore_pooled_marginal[,3], weights.class0=labels_asia[,3],curve=TRUE)
PRROC_obj4 <- pr.curve(scores.class0 = intscore_pooled_vsp[,3], weights.class0=labels_asia[,3],curve=TRUE)
```
